---
- name: set access password option
  lineinfile:
    dest: "{{ redis_conf_file }}"
    regexp: "^# requirepass"
    line: "requirepass {{ redis_password }}"
    state: present
    backrefs: yes
  notify: restart redis

- name: set bind option
  lineinfile:
    dest: "{{ redis_conf_file }}"
    regexp: "^bind "
    line: "bind 127.0.0.1 ::1 {{ redis_ip }}"
    state: present
    backrefs: yes
  notify: restart redis
