---
- name: install apt required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_required_packages }}"

- name: install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: add grafana key
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg
    state: present

- name: add grafana repository
  become: true
  apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present
    update_cache: yes

- name: install grafana
  become: true
  package:
    name: grafana
    state: present
