---
- name: install sentry
  become: yes
  notify: restart sentry
  command:
    chdir: "{{ sentry_dir }}"
    cmd: "{{ sentry_dir }}/install.sh"
  # See https://github.com/getsentry/onpremise/issues/412
  # environment:
  #   SENTRY_IMAGE: "getsentry/sentry:{{ sentry_version }}"

- name: restart sentry
  become: yes
  service:
    name: sentry
    state: restarted
    enabled: yes
