kind: pipeline
type: docker
name: default

steps:
  - name: release
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_api_key
      base_url: https://git.ironlabs.com
      title: ${DRONE_TAG}
      note: CHANGELOG
    when:
      event: tag
  - name: notify
    image: drillster/drone-email
    environment:
      PLUGIN_PASSWORD:
        from_secret: smtp_password
      PLUGIN_HOST: smtp.mailgun.org
      PLUGIN_USERNAME: postmaster@ci.ironlabs.com
      PLUGIN_FROM: no-reply@ci.ironlabs.com
    when:
      status: failure
