---
- name: Configure ldap.conf
  notify: restart slapd
  template:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf

- name: Configure database hash format
  ldap_attr:
    state: exact
    dn: cn=config
    name: olcPasswordCryptSaltFormat
    values: "$6$rounds=656000$%.16s"

- name: Configure database hash
  ldap_attr:
    state: exact
    dn: olcDatabase={-1}frontend,cn=config
    name: "{{ item.name }}"
    values: "{{ item.value }}"
  with_items:
    - name: olcPasswordHash
      value: "{CRYPT}"

- name: Configure base DN
  ldap_attr:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    name: "{{ item.name }}"
    values: "{{ item.value }}"
  with_items:
    - name: olcSuffix
      value: "{{ ldap_base }}"

# - name: Configure LDAP modules
#   ldap_entry:
#     state: present
#     dn: cn=module{1},cn=config
#     objectClass: olcModuleList
#     attributes:
#       olcModulePath: /usr/lib/ldap
#       olcModuleLoad:
#         - memberof
#         - refint

# - name: Configure LDAP memberof overlay
#   ldap_entry:
#     state: present
#     dn: olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config
#     objectClass:
#       - olcConfig
#       - olcMemberOf
#       - olcOverlayConfig
#       - top
#     attributes:
#       olcOverlay: memberof
#       olcMemberOfRefInt: "TRUE"
#       olcMemberOfGroupOC: groupOfNames
#       olcMemberOfMemberAD: member
#       olcMemberOfMemberOfAD: memberOf

# - name: Configure LDAP refint overlay
#   ldap_entry:
#     state: present
#     dn: olcOverlay={1}refint,olcDatabase={1}mdb,cn=config
#     objectClass:
#       - olcConfig
#       - olcRefintConfig
#       - olcOverlayConfig
#       - top
#     attributes:
#       olcOverlay: "refint"
#       olcRefintAttribute: memberof member manager owner
