---
- name: Configure ldap.conf
  become: yes
  notify: restart slapd
  template:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
    mode: 0744

- name: Configure database hash format
  become: yes
  ldap_attrs:
    state: exact
    dn: cn=config
    attributes:
      olcPasswordCryptSaltFormat: "$6$rounds=656000$%.16s"

- name: Configure database hash
  become: yes
  ldap_attrs:
    state: exact
    dn: olcDatabase={-1}frontend,cn=config
    attributes:
      olcPasswordHash: "{CRYPT}"

- name: Configure base DN
  become: yes
  ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcSuffix: "{{ ldap_base }}"

- name: Configure LDAP modules
  become: yes
  ldap_entry:
    state: present
    dn: cn=module{1},cn=config
    objectClass: olcModuleList
    attributes:
      olcModulePath: /usr/lib/ldap
      olcModuleLoad:
        - memberof
        - refint

- name: Configure LDAP memberof overlay
  become: yes
  ldap_entry:
    state: present
    dn: olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcMemberOf
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: memberof
      olcMemberOfRefInt: "TRUE"
      olcMemberOfGroupOC: groupOfNames
      olcMemberOfMemberAD: member
      olcMemberOfMemberOfAD: memberOf

- name: Configure LDAP refint overlay
  become: yes
  ldap_entry:
    state: present
    dn: olcOverlay={1}refint,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcRefintConfig
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: "refint"
      olcRefintAttribute: memberof member manager owner
