---
- name: Install LDAP dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - slapd
      - ldap-utils
      - python-ldap
      - python-ldap3

- name: Start slapd
  systemd:
    name: slapd
    state: started
    enabled: yes
    masked: no
