---
- include_tasks: deps.yml
- include_tasks: config.yml
- include_tasks: structure.yml
- include_tasks: organization.yml
- include_tasks: users.yml
  tags:
    - users

- include_role:
    name: traefik
  vars:
    file_config: "yes"
    label: "ldap"
    domain: "{{ ldap_domain }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    http_port: "80"
