---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: instance-node-exporter
    image: docker.io/ubuntu:18.04
    privileged: true
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
