---
- name: install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: create goaccess directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: 0770
  with_items:
    - "{{ goaccess_dir }}"
    - "{{ goaccess_config_dir }}"
    - "{{ goaccess_html_dir }}"
    - "{{ goaccess_data_dir }}"
    - "{{ goaccess_data_project_dir }}"
    - "{{ goaccess_geoip_dir }}"

- name: download goaccess
  get_url:
    url: "{{ goaccess_download_url }}"
    dest: "{{ goaccess_dir }}/{{ goaccess_download_file }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  run_once: true
  check_mode: false

- name: unpack goaccess
  unarchive:
    src: "{{ goaccess_dir }}/{{ goaccess_download_file }}"
    dest: "{{ goaccess_dir }}"
    creates: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"
    remote_src: "yes"
  check_mode: false

- block:
  - name: configure goaccess build
    command: ./configure --enable-utf8 --enable-geoip=mmdb
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"

  - name: make goaccess build
    become: true
    command: make
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"

  - name: install goaccess
    become: true
    command: make install
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"
    notify: restart goaccess
  when: _download_archive.changed

- name: download geoip city database
  get_url:
    url: "{{ geoip_city_download_url }}"
    dest: "{{ goaccess_geoip_dir }}"
  register: _download_geoip
  until: _download_geoip is succeeded
  retries: 5
  delay: 2
  run_once: true
  check_mode: false

- block:
  - name: unpack geoip city database
    unarchive:
      src: "{{ _download_geoip.dest }}"
      dest: "{{ goaccess_geoip_dir }}"
      remote_src: "yes"
    check_mode: false

  - name: move geoip city file
    copy:
      src: "{{ _download_geoip.dest | regex_replace('.tar.gz') }}/{{ geoip_city_file }}"
      dest: "{{ goaccess_geoip_file }}"
      remote_src: "yes"
      mode: 0770
  when: _download_geoip.changed
