---
- name: install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: create goaccess directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: 0770
  with_items:
    - "{{ goaccess_dir }}"
    - "{{ goaccess_config_dir }}"
    - "{{ goaccess_html_dir }}"
    - "{{ goaccess_data_dir }}"

- name: download goaccess
  get_url:
    url: "{{ goaccess_download_url }}"
    dest: "{{ goaccess_dir }}/{{ goaccess_download_file }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  run_once: true
  check_mode: false

- name: unpack goaccess
  unarchive:
    src: "{{ goaccess_dir }}/{{ goaccess_download_file }}"
    dest: "{{ goaccess_dir }}"
    creates: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"
    remote_src: "yes"
  check_mode: false

- block:
  - name: configure goaccess build
    command: ./configure --enable-utf8
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"

  - name: make goaccess build
    become: true
    command: make
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"

  - name: install goaccess
    become: true
    command: make install
    args:
      chdir: "{{ goaccess_dir }}/goaccess-{{ goaccess_version }}"
    notify: restart goaccess
  when: _download_archive.changed
