---
- name: restart goaccess filter
  service:
    name: "{{ goaccess_filter_service }}"
    state: restarted
    daemon_reload: "yes"

- name: restart goaccess
  service:
    name: "{{ goaccess_service }}"
    state: restarted
    daemon_reload: "yes"
