---
- name: restart gitea
  service:
    name: gitea
    state: restarted

- name: set gitea auth
  command: "{{ gitea_bin | dirname }}/scripts/auth.sh"

- name: set gitea oauth
  command: "{{ gitea_bin | dirname }}/scripts/oauth.sh"
