---
- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    alertmanager_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', 'https://github.com/prometheus/alertmanager/releases/download/v' + alertmanager_version + '/sha256sums.txt', wantlist=True) | list }}"
  when: "('linux-' + go_arch + '.tar.gz') in item"

- name: Fail when extra config flags are duplicating ansible variables
  fail:
    msg: "Detected duplicate configuration entry. Please check your ansible variables and role README.md."
  when:
    (alertmanager_config_flags_extra['config.file'] is defined) or
    (alertmanager_config_flags_extra['storage.path'] is defined) or
    (alertmanager_config_flags_extra['web.listen-address'] is defined) or
    (alertmanager_config_flags_extra['web.external-url'] is defined)

- name: Fail when there are no receivers defined
  fail:
    msg: "Configure alert receivers (`alertmanager_receivers`). Otherwise alertmanager won't know where to send alerts."
  when: alertmanager_receivers == []

- name: Fail when there is no alert route defined
  fail:
    msg: "Configure alert routing (`alertmanager_route`). Otherwise alertmanager won't know how to send alerts."
  when: alertmanager_route == {}

- name: Fail when child routes are defined not in proper place
  fail:
    msg: "Please recofigure `alertmanager_route` a way in which child routes are placed in `alertmanager_child_routes`."
  when: alertmanager_route.routes is defined
