---
- name: gitea config file
  notify: restart gitea
  become: yes
  template:
    src: gitea.ini.j2
    dest: "{{ gitea_config_dir }}/app.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    mode: 0664

- name: admin auth script
  become: yes
  template:
    src: gitea.auth.script.j2
    dest: "{{ gitea_scripts_dir }}/auth.sh"
    owner: root
    group: root
    mode: 0770
  notify: set gitea auth

- name: override home page
  become: yes
  copy:
    src: files/home.tmpl
    dest: "{{ gitea_custom_dir }}/templates/home.tmpl"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
  notify: restart gitea
