---
- name: create admin user script
  become: true
  template:
    src: gitea.create_user.script.j2
    dest: "{{ gitea_bin | dirname }}/scripts/create_user.sh"
    owner: root
    group: root
    mode: 0770
  notify: set gitea create_user
  register: user_created
  tags: gitea

- debug:
    var: user_created

- name: create user oauth application record
  postgresql_query:
    db: "{{ gitea_database_name }}"
    login_user: "{{ gitea_database_user }}"
    login_password: "{{ gitea_database_password }}"
    query: INSERT INTO oauth2_application (uid, name, client_id, client_secret, redirect_uris) values(1, %s, %s, %s, %s)
    positional_args:
      - "CI/CD"
      - "{{ gitea_oauth_key }}"
      - "{{ gitea_oauth_secret }}"
      - "https://{{ drone_domain }}/login"
  when: user_created is defined
