---
- name: install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: install required libraries
  become: yes
  pip:
    name: "{{ python_pip_packages }}"
    state: present

- name: create gitea group
  become: yes
  group:
    name: "{{ gitea_group }}"
    state: present

- name: create gitea user
  become: yes
  user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_working_dir }}"
    comment: Gitea

- name: make sure all relevant gitea directories exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755  # TODO check if this correct mode for /etc/gitea /home/gitea
    recurse: yes
  with_items: "{{ gitea_dirs }}"

- name: download gitea binary
  become: yes
  get_url:
    url: "{{ gitea_download_url }}"
    dest: "{{ gitea_bin }}-{{ gitea_version }}"
    force: no

- name: link gitea binary
  become: yes
  file:
    path: "{{ gitea_bin }}"
    src: "{{ gitea_bin }}-{{ gitea_version }}"
    state: link
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0755

- name: create the gitea systemd service file
  become: yes
  template:
    src: gitea.service.j2
    dest: "{{ systemd_units_dir }}/gitea.service"
  notify: restart gitea
