---
- name: ensure systemd-tmpfiles dir exists
  file:
    path: /etc/tmpfiles.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create djangoapp directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ celery_user }}"
    group: "{{ celery_group }}"
    mode: 0755
    recurse: yes
  with_items: "{{ celery_dirs }}"
