---
- name: Install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: install required libraries
  become: yes
  pip:
    name: "{{ python_pip_packages }}"
    state: present

- name: create drone group
  become: yes
  group:
    name: "{{ drone_group }}"
    state: present

- name: create drone user
  become: yes
  user:
    name: "{{ drone_user }}"
    group: "{{ drone_group }}"
    home: "{{ drone_working_dir }}"
    groups: docker
    append: yes

- name: make sure relevant directories exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ drone_config_dir }}"
    - "{{ drone_working_dir }}/data"

- name: download drone cli
  become: yes
  unarchive:
    src: "{{ drone_download_url }}"
    dest: "{{ drone_working_dir }}"
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0755
    remote_src: yes

- name: create the drone systemd service file
  become: yes
  template:
    src: drone.service.j2
    dest: "{{ systemd_units_dir }}/drone.service"
  notify: restart drone
