---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ drone_packages }}"

- name: create drone group
  group:
    name: "{{ drone_group }}"
    state: present

- name: create drone user
  user:
    name: "{{ drone_user }}"
    group: "{{ drone_group }}"
    home: "{{ drone_working_dir }}"
    groups: docker
    append: yes

- name: make sure relevant directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ drone_config_dir }}"
    - "{{ drone_working_dir }}/data"

- name: download drone cli
  unarchive:
    src: "{{ drone_download_url }}"
    dest: "{{ drone_working_dir }}"
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0755
    remote_src: yes
