---
- name: install required packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_support_packages }}"

- name: download terraform release
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ terraform_user }}"
    group: "{{ terraform_group }}"
    mode: 0755
    remote_src: true
  with_items:
    - url: "{{ terraform_release_url }}"
      dest: "{{ terraform_dir }}"
