---
- name: restart drone server
  docker_container:
    name: drone-server
    restart: yes
  listen: "restart drone"

- name: restart drone runner
  docker_container:
    name: drone-runner
    restart: yes
  listen: "restart drone"
