---
- name: alerting rules file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
  notify:
    - reload prometheus

- name: copy custom alerting rule files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check rules %s"
  with_fileglob: "{{ prometheus_alert_rules_files }}"
  notify:
    - reload prometheus

- name: configure prometheus
  template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "/usr/local/bin/promtool check config %s"
  notify:
    - reload prometheus

- name: copy prometheus custom static targets
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/file_sd/"
    force: true
    owner: root
    group: prometheus
    mode: 0640
  with_fileglob: "{{ prometheus_static_targets_files }}"

- name: config nodes
  template:
    src: nodes.yml.j2
    dest: "{{ prometheus_config_dir }}/file_sd/nodes.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
  notify:
    - reload prometheus

- name: config proxies
  template:
    src: proxies.yml.j2
    dest: "{{ prometheus_config_dir }}/file_sd/proxies.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
  notify:
    - reload prometheus
