---
- include: preflight.yml
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- include: install.yml
  become: true
  tags:
    - prometheus_install

- include: configure.yml
  become: true
  tags:
    - prometheus_configure

- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  tags:
    - prometheus_run

- include_role:
    name: traefik
  vars:
    file_config: "yes"
    label: "{{ prometheus_label }}"
    domain: "{{ prometheus_domain }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    port: "{{ prometheus_web_listen_port }}"
    middlewares: "['auth']"
