---
- name: configure automatic upgrades
  become: yes
  lineinfile:
    dest: "{{ unattended_upgrades_config }}"
    regexp: "^//{{ item.option }}.+$"
    line: "{{ item.option }} \"{{ item.value }}\";"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ unattended_upgrades_config_options }}"

- name: set auto-upgrades config
  become: yes
  template:
    src: "auto-upgrades.j2"
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: pull termite info
  become: yes
  get_url:
    url: "{{ termite_url }}"
    dest: "{{ termite_dir }}"
    force: no
  register: termite

- name: load termite info
  become: yes
  command:
    cmd: tic -x termite.terminfo
    chdir: "{{ termite_dir }}"
  when: termite.changed
