---
- name: Ensure group "{{ admin_group }}" exists
  become: yes
  group:
    name: "{{ admin_group }}"
    state: present

- name: Setup users
  become: yes
  user:
    name: "{{ item.username }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    group: "{{ admin_group }}"
    remove: yes
  with_items:
    - "{{ users }}"
  when: item.is_admin|bool
  no_log: true
  tags: users

- name: Add SSH-keys to users
  become: yes
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - public_keys.active
    - flags:
      skip_missing: "yes"
  when: item.0.state != "absent"
  tags: users

- name: Remove old SSH-keys from users
  become: yes
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ users }}"
    - public_keys.disabled
    - flags:
      skip_missing: "yes"
  when: item.0.state != "absent"
  tags: users

- name: Add admin group to sudoers
  become: yes
  lineinfile:
    dest=/etc/sudoers
    regexp="^%{{ admin_group }}"
    line="%{{ admin_group }} ALL=(ALL) NOPASSWD:ALL"

- name: Disable Requiretty from sudoers
  become: yes
  lineinfile:
    dest=/etc/sudoers
    regexp="Defaults    requiretty"
    line="#Defaults    requiretty"
