---
- name: create traefik directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_dir }}"
    - "{{ traefik_config_dir }}"
    - "{{ traefik_log_dir }}"

- name: download traefik binary
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
    remote_src: true
    exclude:
      - CHANGELOG.md
      - LICENSE.md
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_install_dir }}"
  notify: restart traefik
